#!/bin/sh

echo 'OK Pleased to meet you'

while read stdin; do
	case `echo $stdin | tr '[:lower:]' '[:upper:]'` in
		BYE) break ;;
		GETPIN) echo "D `DISPLAY=:0 dmenu -P -p passphrase $*`\nOK" ;;
		*) echo OK
	esac
done
